name: zxplayer

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:

  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Install Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.0
          cache: 'yarn'
      - name: Clone source code
        run: |
          pwd
          git clone --depth=1 https://github.com/hjdhnx/ZyPlayer.git 
          cd ZyPlayer
          yarn add electron-vite -D
          yarn build:linux
          cp ./dist/*.AppImage ../
          cd ../
          rm -rf ZyPlayer/
      - name: commit
        id: commit
        run: |
          git config --global user.email 2486251172@qq.com
          git config --global user.name hbyhzx
          git add .
          git commit -m "APP"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: Upload packages
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: zyplayer-linux-appimage
          path: ./dist
   
      - name: Upload Firmware to Github Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist/*.AppImage*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
