name: Build/release

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Clone source code
        run: |
          git clone --depth=1 https://github.com/hjdhnx/ZyPlayer.git 
          cd ZyPlayer
      - name: Install Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.0
          cache: 'yarn'

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # build_script_name: 'electron:prebuild'
          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}


      - name: Upload Artifact (Linux AppImage)
        uses: actions/upload-artifact@v4
        with:
          name: zyplayer-linux-appimage
          path: ./dist/*.AppImage
          if-no-files-found: ignore

      - name: Upload Artifact (Linux deb)
        uses: actions/upload-artifact@v4
        with:
          name: zyplayer-linux-deb
          path: ./dist/*.deb
          if-no-files-found: ignore




# name: zxplayer

# on:
#   workflow_dispatch:
#   release:
#     types: [published]
#   push:
#     tags:
#     - 'v*'
#   #  branches: 
#   #    - master
# #  schedule:
# #    - cron: 0 8 * * 5
#   watch:
#     types: [started]

# jobs:

#   build:
#     runs-on: ubuntu-20.04
#     if: github.event.repository.owner.id == github.event.sender.id
#     steps:
#       - name: Check out Git repository
#         uses: actions/checkout@v4
#         with:
#           submodules: "recursive"
#       - name: Clone source code
#         run: |
#           GH_TOKEN = ${{ secrets.GITEE_TOKEN }}
#           pwd
#           git clone --depth=1 https://github.com/hjdhnx/ZyPlayer.git 
#           cd ZyPlayer
#           yarn add electron-vite -D
#           yarn build:linux
#           ls
#       - name: Install Node.js 18.x
#         uses: actions/setup-node@v4
#         with:
#           node-version: 18.18.0
#           cache: 'yarn'
#       - name: Push changes
#         uses: ad-m/github-push-action@master
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           branch: ${{ github.ref }}
#       - name : Upload packages
#         uses: actions/upload-artifact@master
#         if: always()
#         with:
#           name: zyplayer-linux-appimage
#           path: ./dist
   
#       - name: Upload Firmware to Github Release
#         uses: svenstaro/upload-release-action@v2
#         with:
#           repo_token: ${{ secrets.GITHUB_TOKEN }}
#           file: ./dist/*.AppImage*
#           tag: ${{ github.ref }}
#           overwrite: true
#           file_glob: true
